name: beyondgaming
favicon: null
layout_spectrum: 0.36707099294289947
typography_spectrum: 0.44342366652563214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9709890543017536
  lightness: 0.8514212411828339
  saturation: 0.18784332578070462
  rhythmicContrast: 0.9117927879560739
purpose: []
